# Generated by Django 5.2.8 on 2025-11-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailotp_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
