# Generated by Django 5.2.8 on 2025-11-21 18:16

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/', validators=[catalog.validators.validate_ebook_file_extension, catalog.validators.validate_ebook_file_size]),
        ),
    ]
