# Generated by Django 5.2.8 on 2025-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_password',
            field=models.CharField(blank=True, help_text='Password to open the protected PDF (optional).', max_length=64),
        ),
    ]
