# Generated by Django 5.2.8 on 2025-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
