# Generated by Django 5.2.8 on 2025-11-21 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Optional note from customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_number',
            field=models.CharField(blank=True, help_text="Customer's bKash/Nagad number", max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('manual_bkash', 'Manual bKash'), ('manual_nagad', 'Manual Nagad'), ('other', 'Other')], default='manual_bkash', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Review'), ('success', 'Success'), ('failed', 'Failed / Cancelled')], default='initiated', max_length=20),
        ),
    ]
